//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeShopManagerment_DAL.DTO_DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public int scheduleID { get; set; }
        public System.DateTime dateID { get; set; }
        public int staffID { get; set; }
        public string shifts { get; set; }
        public Nullable<double> hoursPerShifts { get; set; }
    
        public virtual dateTable dateTable { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
